namespace PlanStack.Shared.Enums
{
    public enum RuleSetDefinitionEnum : int
    {
        BY_DISTANCE = 0,

        BY_BLUEPRINT_AREA_OVER_RATIO = 1,
        BY_BLUEPRINT_AREA_EXACT_RATIO = 2,
        BY_BLUEPRINT_AREA_UNDER_RATIO = 3,

        BY_COMPONENT_IN_ROOM_AREA_UNDER_RATIO = 4,
        BY_COMPONENT_IN_ROOM_AREA_EXACT_RATIO = 5,
        BY_COMPONENT_IN_ROOM_AREA_OVER_RATIO = 6,

        BY_ROOM_AREA_SIZE_OVER_RATIO = 11,
        BY_ROOM_AREA_SIZE_UNDER_RATIO = 12,
        BY_ROOM_AREA_SIZE_EXACT_RATIO = 13,

        BY_TOTAL_QUANTITY_UNDER_RATIO = 7,
        BY_TOTAL_QUANTITY_OVER_RATIO = 8,

        BY_OCCUPANCY_OVER_RATIO = 9,
        BY_OCCUPANCY_UNDER_RATIO = 10,

        OTHER = 99
    }
}
