namespace PlanStack.Shared.Enums
{
    public enum RuleSetDefinitionEnum : int
    {
        BY_ROOM_QUANTITY_IN_BLUEPRINT = 0,
        BY_BATHROOM_QUANTITY_IN_BLUEPRINT = 1,
        BY_LIVING_ROOM_QUANTITY_IN_BLUEPRINT = 2,
        BY_KITCHEN_QUANTITY_IN_BLUEPRINT = 3,
        BY_DINING_ROOM_QUANTITY_IN_BLUEPRINT = 7,
        BY_OFFICE_QUANTITY_IN_BLUEPRINT = 8,
        BY_BEDROOM_QUANTITY_IN_BLUEPRINT = 18,

        BY_COMPONENT_QUANTITY_IN_ROOM = 19,
        BY_COMPONENT_QUANTITY_IN_BATHROOM = 20,
        BY_COMPONENT_QUANTITY_IN_LIVING_ROOM = 21,
        BY_COMPONENT_QUANTITY_IN_KITCHEN = 22,
        BY_COMPONENT_QUANTITY_IN_DINING_ROOM = 23,
        BY_COMPONENT_QUANTITY_IN_OFFICE = 24,
        BY_COMPONENT_QUANTITY_IN_BEDROOM = 25,

        BY_COMPONENT_IN_ROOM_AREA_UNDER_RATIO = 4,
        BY_COMPONENT_IN_ROOM_AREA_EXACT_RATIO = 5,
        BY_COMPONENT_IN_ROOM_AREA_OVER_RATIO = 6,

        BY_ROOM_AREA_SIZE_OVER_RATIO = 11,
        BY_BATHROOM_AREA_SIZE_OVER_RATIO = 12,
        BY_LIVING_ROOM_AREA_SIZE_OVER_RATIO = 13,
        BY_KITCHEN_AREA_SIZE_OVER_RATIO = 14,
        BY_DINING_ROOM_AREA_SIZE_OVER_RATIO = 15,
        BY_OFFICE_AREA_SIZE_OVER_RATIO = 16,
        BY_BEDROOM_AREA_SIZE_OVER_RATIO = 17,

        BY_COMPONENT_QUANTITY_PER_OCCUPANCY = 9,

        OTHER = 99
    }
}
